build-job:
  stage: build
  tags: 
    - shell
  script:
    - docker build -t docker-repo.bodc.me/colsau/imfe-pilot/frontend:latest .

deploy-job:
  stage: deploy
  tags:
      - shell
  script:
#    - docker push docker-repo.bodc.me/colsau/imfe-pilot/frontend:latest
#    - ssh web 'docker pull docker-repo.bodc.me/colsau/imfe-pilot/frontend:latest
     - docker save docker-repo.bodc.me/colsau/imfe-pilot/frontend | gzip -c - > frontend.tar.gz
     - scp frontend.tar.gz web:/home/gitlab-runner/
     - ssh web "gunzip -c frontend.tar.gz | docker import --change 'CMD [\"nginx\",\"-g\",\"daemon off;\"]' - docker-repo.bodc.me/colsau/imfe-pilot/frontend:latest"
     - ssh web 'docker stop frontend && docker run -d -p 8080:80 --name frontend docker-repo.bodc.me/colsau/imfe-pilot/frontend:latest'
