apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: uk-london-1.ocir.io/lrl8vbuxj1ma/frontend:latest
          ports:
            - containerPort: 80  # Adjust the port as needed
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer  # Use LoadBalancer for external access